# Change 'comments' to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'penggaris-jangka'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: 'UA-80851323-2'

menu:
- {name: 'Tentang', path: 'menu', url: 'about.html'}
- {name: 'Tulisan', path: 'menu', url: 'writing.html'}
- {name: 'Kontak', path: 'menu', url: 'contact.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'github', link: 'https://www.github.com/rud72k'}
- {icon: 'twitter', link: 'https://twitter.com/prihandokorudi'}
- {icon: 'facebook', link: 'https://twitter.com/ruuds'}
- {icon: 'linkedin', link: 'http://www.linkedin.com/in/prihandoko/'}
- {icon: 'envelope', link: 'mailto:prihandokorudi@gmail.com'}
- {icon: 'rss-square', link: '/feed.xml'}
# - {icon: 'rss-square', link: '/rss-feed.xml'}

# Customize site text
pagination:
  next_page: 'Selanjutnya'
  previous_page: 'Sebelumnya'

sharing_button_prompt: 'Feel free to share!'

related_posts: 'Kamu mungkin tertarik membaca:'

post_date_prefix: 'Ditulis pada'
